name: Update Blog

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Clone dependencies
        run: |
          git clone https://github.com/girisagar46/Flex.git themes/Flex
          git clone https://github.com/getpelican/pelican-plugins
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and publish the blog
        run: |
          invoke publish
