name: Update Blog

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Clone dependencies
        run: |
          git clone https://github.com/girisagar46/girisagar46.github.io-theme.git themes/girisagar46.github.io-theme
          git clone https://github.com/getpelican/pelican-plugins
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and publish the blog
        run: |
          invoke publish
